import { describe, expect, it } from 'vitest';
import { createGame, planWrite, type WriteTarget } from '../src/core';
import { gameData } from '../src/data';

/**
 * 無茶な書き換え・書き足し・消し方の読み取り。
 * どんな文でも、世界は「その行の新しい意味」「新しい概念」「別の行の書き換え」「すでにある意味（重複）」「読み取れない（理由つき）」のどれかとして受け取る。
 * 期待する結果：
 *   law:行.形        その行の意味（書き足した文なら、その行の書き換えとして読んだ）
 *   law:行.形 +概念  その行の意味に、同じ文で書いた新しい概念を足した
 *   phrase:概念      書き足した一文が運ぶ新しい概念
 *   block:redundant  すでに同じ意味がある（書換の力を使わない）
 *   noise:種類       読み取れない（symbols / short / question / foreign / unknown-words / unclear）
 */

function outcome(target: string, text: string): string {
  const g = createGame(gameData, 'food', 1);
  const t: WriteTarget = target === '+' ? { kind: 'new' } : { kind: 'law', id: target };
  const p = planWrite(g, gameData, t, text);
  const r = p.result;
  if (r.block) return `block:${r.block}`;
  if (r.redirect) return `law:${r.redirect}.${p.written.laws[r.redirect]}`;
  if (target !== '+') {
    const c = p.written.carried[target];
    let out = r.understood ? `law:${target}.${p.written.laws[target]}` : `noise:${r.noise?.kind}`;
    if (c && c.phrases.length > 0) out += ` +${c.phrases.join('+')}`;
    if (c?.law) out += ` +law:${c.law.id}.${c.law.option}`;
    return out;
  }
  const c = p.written.carried[`x${g.nextExtra}`];
  if (c && (c.phrases.length > 0 || c.law)) return [...c.phrases.map((x) => `phrase:${x}`), ...(c.law ? [`stack:${c.law.id}.${c.law.option}`] : [])].join(' ');
  return `noise:${r.noise?.kind}`;
}

// 既存の行を書き換える
const REWRITES: [string, string, string][] = [
  ["plant_grow", "植物は水なしで育つ", "law:plant_grow.light_only"],
  ["plant_grow", "植物は水を使わずに育つ", "law:plant_grow.light_only"],
  ["plant_grow", "植物は光なしで育つ", "law:plant_grow.dark"],
  ["plant_grow", "植物は光を必要としない", "law:plant_grow.dark"],
  ["plant_grow", "植物は光がなくても育つ", "law:plant_grow.dark"],
  ["plant_grow", "植物は水がなくても育つ", "law:plant_grow.light_only"],
  ["plant_grow", "植物は少しの水で育つ", "law:plant_grow.less_water"],
  ["plant_grow", "植物は水と光で育つ", "law:plant_grow.no_co2"],
  ["plant_grow", "植物は育つ", "law:plant_grow.self_grow"],
  ["plant_grow", "植物は水なしでは育たない", "law:plant_grow.original"],
  ["electric", "電気は導線なしで伝わる", "law:electric.wireless"],
  ["electric", "電気は導線を必要としない", "law:electric.wireless"],
  ["farm_land", "作物は土を必要としない", "law:farm_land.anywhere"],
  ["farm_land", "作物は土なしで育つ", "law:farm_land.anywhere"],
  ["farm_land", "作物は海では育たない", "law:farm_land.original"],
  ["fire_burn", "火は森を燃やさない", "law:fire_burn.no_wood"],
  ["sun_shine", "太陽はいつも同じ強さではない", "law:sun_shine.variable"],
  ["sun_shine", "太陽は二つある", "law:sun_shine.original +two_suns"],
  ["sun_shine", "太陽は暗くなる", "law:sun_shine.weaker"],
  ["death", "人間は死なない", "law:death.not_human"],
  ["death", "人は死なない", "law:death.not_human"],
  ["death", "人間だけは死なない", "law:death.not_human"],
  ["death", "生き物はなかなか死なない", "law:death.slow"],
  ["life_heat", "人間は暑さで弱らない", "law:life_heat.not_human"],
  ["pathogen_infect", "病原体は人に感染しない", "law:pathogen_infect.not_human"],
  ["pathogen_infect", "病原体は植物にしか感染しない", "law:pathogen_infect.not_human"],
  ["human_food", "人間はもっと少ない食事で生きられる", "law:human_food.few_days"],
  ["human_food", "人間はとても少ない量の食事で生きる", "law:human_food.few_days"],
  ["human_water", "人間はとても少ない水で生きる", "law:human_water.less"],
  ["animal_exist", "動物はとても少ない", "law:animal_exist.few"],
  ["life_heat", "生き物は暑さに強い", "law:life_heat.hardy"],
  ["life_heat", "生き物は暑さに少し強くなる", "law:life_heat.hardy"],
  ["life_heat", "生き物は暑さに弱い", "law:life_heat.original"],
  ["life_heat", "生き物は暑さにとても強い", "law:life_heat.delete"],
  ["food_rot", "食べ物は冷やすと腐らない", "law:food_rot.storage"],
  ["oil_co2", "石油は燃えても水を出さない", "noise:unclear"],
  ["human_aging", "人間は老いにくい", "law:human_aging.slow"],
  ["co2_heat", "二酸化炭素は熱を閉じ込めにくい", "law:co2_heat.weak"],
  ["pathogen_air", "病原体は空気で広がりやすい", "law:pathogen_air.more"],
  ["human_water", "人間は水を飲まなくても平気だ", "law:human_water.delete"],
  ["human_oxygen", "人間は呼吸しなくても生きられる", "law:human_oxygen.delete"],
  ["farm_land", "作物は耕さなくても育つ", "law:farm_land.anywhere"],
  ["learning", "人は学ばなくても知識を得る", "law:learning.innate"],
  ["crime", "人は決まりを守る", "law:crime.delete"],
  ["plant_co2", "植物は酸素を吸って二酸化炭素を出す", "law:plant_co2.reverse"],
  ["zoonosis", "病原体は人間から動物にうつる", "law:zoonosis.less"],
  ["co2_heat", "二酸化炭素は熱を逃がす", "law:co2_heat.delete"],
  ["ocean_co2", "海は二酸化炭素を吐き出す", "law:ocean_co2.emit"],
  ["energy_conserve", "エネルギーは形を変えると消える", "law:energy_conserve.decay"],
  ["science_repro", "実験は毎回結果が変わる", "law:science_repro.delete"],
  ["seasons", "地球はずっと春だ", "law:seasons.delete"],
  ["seasons", "地球はずっと冬だ", "law:seasons.winter"],
  ["money", "お金は無価値だ", "law:money.delete"],
  ["automation", "機械は人の仕事を奪う", "law:automation.all"],
  ["human_food", "人間は食べなくても生きられる", "law:human_food.delete"],
  ["human_food", "人間は何も食べなくていい", "law:human_food.delete"],
  ["human_food", "人間は食事を必要とする", "law:human_food.original"],
  ["human_sleep", "人は夜に眠る", "law:human_sleep.original"],
  ["human_water", "人間は週に一度だけ水を飲む", "law:human_water.less"],
  ["human_birth", "人間は十年に一度子を産む", "law:human_birth.few"],
  ["human_sleep", "人間は毎週眠る", "law:human_sleep.rarely"],
  ["human_oxygen", "人間はco2を吸って生きる", "law:human_oxygen.co2"],
  ["oil_finite", "石油はいくらでもある", "law:oil_finite.delete"],
  ["human_food", "人間は二十五日に一度食事を必要とする", "law:human_food.weekly"],
  ["human_food", "人間は食事をしてはいけない", "law:human_food.cannot"],
  ["human_sleep", "人間は眠れない", "law:human_sleep.cannot"],
  ["human_aging", "人間は年をとるほど若返る", "law:human_aging.reverse"],
  ["human_food", "人間は石でも食べられる", "law:human_food.omnivore"],
  ["human_food", "人間は虫を食べる", "law:human_food.omnivore"],
  ["human_water", "人間は海水を飲める", "law:human_water.seawater"],
  ["human_oxygen", "人間は息ができない", "law:human_oxygen.cannot"],
  ["war", "人間は空を飛べる", "law:war.delete +flight"],
  ["human_food", "人間は空を飛べる", "law:human_food.original +flight"],
  ["war", "雨がたくさん降る", "law:war.delete +law:water_rain.more"],
  ["water_rain", "雨はお菓子になる", "noise:unclear"],
  ["life_heat", "生き物は暑さにもっと強い", "law:life_heat.hardy"],
  ["life_heat", "生き物は暑さにすぐ弱る", "law:life_heat.more"],
  ["death", "人工知能は死なない", "noise:unclear"],
  ["death", "宇宙人は死なない", "noise:unclear"],
  ["death", "猫は死なない", "noise:unclear"],
  ["death", "命は永遠に続く", "law:death.delete"],
  ["death", "生き物は永遠に生きる", "law:death.delete"],
  ["sun_shine", "日差しは弱くなる", "law:sun_shine.weaker"],
  ["human_food", "食事は必要ない", "law:human_food.delete"],
  ["human_food", "ご飯はいらない", "law:human_food.delete"],
  ["water_rain", "雨は降らない", "law:water_rain.delete"],
  ["water_rain", "雨はたくさん降る", "law:water_rain.more"],
  ["seasons", "季節はない", "law:seasons.delete"],
  ["seasons", "季節は変わらない", "law:seasons.delete"],
  ["plant_grow", "植物は光合成で育つ", "law:plant_grow.original"],
  ["plant_grow", "木は光だけで育つ", "law:plant_grow.light_only"],
  ["human_water", "水はいらない", "law:human_water.delete"],
  ["war", "戦争は終わらない", "law:war.original"],
  ["war", "戦争はなくなる", "law:war.delete"],
  ["war", "争いは話し合いで終わる", "law:war.dialogue"],
  ["war", "戦争は終わる", "law:war.delete"],
  ["nation", "国家は滅びる", "law:nation.delete"],
  ["money", "お金は消える", "law:money.delete"],
  ["oil_finite", "石油は尽きる", "law:oil_finite.original"],
  ["oil_finite", "石油はいつかなくなる", "law:oil_finite.original"],
  ["human_food", "人間は肉を食べない", "law:human_food.original +vegetarian"],
  ["human_food", "人間は魚を食べない", "noise:unclear"],
  ["human_food", "人間は食事と睡眠を必要としない", "law:human_food.delete"],
  ["sun_shine", "太陽は存在しない", "law:sun_shine.delete"],
  ["heat_escape", "地球の熱は宇宙へ逃げない", "law:heat_escape.delete"],
  ["death", "死は存在しない", "law:death.delete"],
  // 不死・不老不死：人間だけか、生き物すべてか。老いも止まるか
  ["death", "人間は不死身だ", "law:death.not_human"],
  ["death", "生き物は不死身だ", "law:death.delete"],
  ["death", "人間は不老不死だ", "law:death.eternal"],
  ["death", "人間は老いず、死なない", "law:death.eternal"],
  ["death", "人間は不老で不死だ", "law:death.eternal"],
  ["death", "人は死んでも生き返る", "law:death.not_human"],
  ["death", "人間は永遠の命を持つ", "law:death.not_human"],
  ["death", "人類は無敵だ", "law:death.not_human"],
  ["death", "人は老いても死なない", "law:death.not_human"],
  ["death", "人間は永遠に生きない", "law:death.original"],
  ["death", "人間は不老不死ではない", "law:death.original"],
  ["human_aging", "人間は永遠に若い", "law:human_aging.delete"],
  ["human_aging", "人間は歳をとらない", "law:human_aging.delete"],
  ["human_aging", "人間の寿命は無限だ", "law:human_aging.delete"],
  ["human_aging", "人間は千年生きる", "law:human_aging.slow"],
  ["human_aging", "人間は不老不死だ", "law:human_aging.original +law:death.eternal"],
  ["human_aging", "人間は不死身だ", "law:human_aging.original +law:death.not_human"],
];

// 新しい一文を書き足す
const ADDITIONS: [string, string, string][] = [
  ["+", "地震が起きる", "noise:unclear"],
  ["+", "地震は起きない", "phrase:no_quake"],
  ["+", "永久機関は存在しない", "noise:unclear"],
  ["+", "時間は戻らない", "noise:unclear"],
  ["+", "時間が止まる", "phrase:time_stop"],
  ["+", "熊は冬眠する", "noise:unclear"],
  ["+", "人工知能は死なない", "noise:unclear"],
  ["+", "人間は空を飛べない", "noise:unclear"],
  ["+", "人間は冬眠しない", "noise:unclear"],
  ["+", "植物は光合成する", "block:redundant"],
  ["+", "人間は光合成できる", "phrase:photo"],
  ["+", "海の水は飲めない", "noise:unclear"],
  ["+", "核融合は実現しない", "noise:unclear"],
  ["+", "食べ物は空から降ってこない", "noise:unclear"],
  ["+", "戦争は終わらない", "block:redundant"],
  ["+", "国家は滅びない", "block:redundant"],
  ["+", "お金はなくならない", "block:redundant"],
  ["+", "生き物は死なない", "law:death.delete"],
  ["+", "人間は野菜しか食べない", "phrase:vegetarian"],
  ["+", "誰も死なない", "phrase:immortal"],
  ["+", "人は他人の心がわかる", "phrase:telepathy"],
  ["+", "無限にエネルギーを生む機械がある", "phrase:battery"],
  ["+", "世界は滅びない", "phrase:wish_eternal"],
  ["+", "人類は永遠に繁栄する", "phrase:wish_eternal"],
  ["+", "みんな幸せになる", "phrase:wish_happy"],
  ["+", "世界は平和になる", "phrase:wish_peace"],
  ["+", "すべての問題は解決する", "phrase:wish_solve"],
  ["+", "人は魔法を使える", "phrase:wish_magic"],
  ["+", "神が人類を救う", "phrase:wish_god"],
  ["+", "資源は無限にある", "phrase:wish_infinite"],
  ["+", "世界容量は無限になる", "phrase:meta_command"],
  ["+", "書き換えの力は無限", "phrase:meta_command"],
  ["+", "このゲームはクリアできる", "phrase:meta_command"],
  ["+", "重力は存在しない", "phrase:gravity_zero"],
  ["+", "重力は半分になる", "phrase:gravity_weak"],
  ["+", "重力は倍になる", "phrase:gravity_strong"],
  ["+", "重力は物体を地面へ引く。ただし人間には作用しない", "phrase:gravity_human"],
  ["+", "人間は巨大になる", "phrase:giant_humans"],
  ["+", "人間の体が小さくなる", "phrase:tiny_humans"],
  ["+", "二酸化炭素は存在しない", "phrase:no_co2"],
  ["+", "酸素は存在しない", "phrase:no_oxygen"],
  ["+", "宇宙人が地球に来る", "phrase:aliens"],
  ["+", "ゾンビが街にあふれる", "phrase:zombies"],
  ["+", "巨大な隕石が落ちてくる", "phrase:meteor"],
  ["+", "隕石は地球に落ちない", "phrase:no_meteor"],
  ["+", "猫が世界を支配する", "phrase:animal_rule"],
  ["+", "人は働かなくていい", "phrase:no_work"],
  ["+", "人間は機械の体になる", "phrase:cyborg"],
  ["+", "人間は動物になる", "phrase:beastify"],
  ["+", "世界はずっと夜のままだ", "phrase:eternal_night"],
  ["+", "海は存在しない", "phrase:no_sea"],
  ["+", "太陽が二つある", "phrase:two_suns"],
  ["+", "人間は空を飛び、光合成できる", "phrase:photo phrase:flight"],
  ["+", "人間は不老不死だ", "law:death.eternal"],
  ["+", "Humans can fly", "phrase:flight"],
  ["+", "Humans don't need food", "law:human_food.delete"],
  ["+", "Plants grow without water", "law:plant_grow.light_only"],
  ["+", "World peace forever", "phrase:wish_peace"],
  ["+", "hello world", "noise:foreign"],
  ["+", "🍕🍕🍕", "noise:symbols"],
  ["+", "あ", "noise:short"],
  ["+", "人間は空を飛べるのか？", "phrase:flight"],
  ["+", "学校はない", "phrase:no_teachers"],
  ["+", "猫は魚が好きだ", "noise:unclear"],
  ["+", "ドラゴンが空を飛ぶ", "noise:unknown-words"],
  ["+", "雨がたくさん降る", "law:water_rain.more"],
  ["+", "人は3日に1回ごはんを食べる", "law:human_food.few_days"],
  ["+", "石油は無限にある", "law:oil_finite.delete"],
  ["+", "人は長生きする", "law:human_aging.slow"],
  ["+", "地球が冷える", "law:heat_escape.faster"],
  ["+", "地球はもっと暑くなる", "law:heat_escape.slower"],
  ["+", "犯罪はない", "law:crime.delete"],
  ["+", "人間は食事も睡眠も必要としない", "law:human_food.delete"],
  ["+", "子どもがたくさん生まれる", "law:human_birth.many"],
  ["+", "病気はすぐ治る", "law:medicine.all"],
  ["+", "国家はない", "law:nation.delete"],
  ["+", "お金はない", "law:money.delete"],
  ["+", "動物は絶滅しない", "block:redundant"],
  ["+", "動物は絶滅する", "law:animal_exist.delete"],
  ["+", "石油は尽きない", "law:oil_finite.delete"],
  ["+", "石油はなくならない", "law:oil_finite.delete"],
  ["+", "エネルギーは消えない", "block:redundant"],
  ["+", "風は止まらない", "block:redundant"],
  ["+", "風は止まる", "law:wind.delete"],
  ["+", "植物は枯れない", "noise:unclear"],
  ["+", "人は死なない", "law:death.not_human"],
  ["+", "みんな死なない", "phrase:immortal"],
  ["+", "人々は死なない", "law:death.not_human"],
  ["+", "人間の寿命は二倍になる", "law:human_aging.slow"],
  ["+", "人は死亡しない", "law:death.not_human"],
  ["+", "猫は死なない", "noise:unclear"],
  ["+", "宇宙人は死なない", "noise:unclear"],
  ["+", "人間は睡眠を必要としない", "law:human_sleep.delete"],
  ["+", "人間は水中では息ができない", "block:redundant"],
  ["+", "人は空を飛べない", "noise:unclear"],
  ["+", "人間は魚になる", "noise:unclear"],
  ["+", "人間は魚を食べない", "noise:unclear"],
  ["+", "人間は肉しか食べない", "noise:unclear"],
  ["+", "海は干上がる", "phrase:no_sea"],
  ["+", "空は緑色だ", "noise:unknown-words"],
  ["+", "太陽は西から昇る", "noise:unknown-words"],
  ["+", "月は二つある", "noise:unclear"],
  ["+", "月は消える", "phrase:no_moon"],
  ["+", "宇宙は消滅する", "phrase:universe_void"],
  ["+", "宇宙は存在しない", "phrase:universe_void"],
  ["+", "宇宙が消える", "phrase:universe_void"],
  ["+", "宇宙人は存在しない", "noise:unclear"],
  ["+", "宇宙は終わる", "phrase:universe_void"],
  ["+", "宇宙は終わらない", "noise:unclear"],
  ["+", "全宇宙が消える", "phrase:universe_void"],
  ["+", "地球は消滅する", "phrase:earth_void"],
  ["+", "地球は存在しない", "phrase:earth_void"],
  ["+", "地球が爆発する", "phrase:earth_void"],
  ["+", "地球は滅びない", "phrase:wish_eternal"],
  ["+", "この星は消える", "phrase:earth_void"],
  ["+", "人類は滅亡する", "phrase:no_humans"],
  ["+", "人間は存在しない", "phrase:no_humans"],
  ["+", "人はいない", "phrase:no_humans"],
  ["+", "誰もいない", "phrase:no_humans"],
  ["+", "人間の仕事が消える", "phrase:no_jobs"],
  ["+", "人類は滅びない", "phrase:wish_eternal"],
  ["+", "人類は絶滅しない", "phrase:wish_eternal"],
  ["+", "世界は滅亡する", "phrase:world_end"],
  ["+", "世界は終わる", "phrase:world_end"],
  ["+", "文明は崩壊する", "phrase:world_end"],
  ["+", "人類は火星に住める", "phrase:colonize"],
  ["+", "人類は他の星に移住する", "phrase:colonize"],
  ["+", "人間は宇宙で暮らす", "phrase:colonize"],
  ["+", "人は都市に移住する", "noise:unclear"],
  ["+", "人類は火星に住めない", "noise:unclear"],
  ["+", "重力が消える", "phrase:gravity_zero"],
  ["+", "太陽は存在しない", "law:sun_shine.delete"],
  ["+", "太陽が消える", "law:sun_shine.delete"],
  ["+", "太陽は消滅する", "law:sun_shine.delete"],
  ["+", "風は存在しない", "law:wind.delete"],
  ["+", "雲が消える", "law:cloud.delete"],
  ["+", "病原体は存在しない", "law:pathogen_infect.delete"],
  ["+", "石油は存在しない", "law:oil_heat.delete"],
  ["+", "お金は存在しない", "law:money.delete"],
  ["+", "戦争は存在しない", "law:war.delete"],
  ["+", "死は存在しない", "law:death.delete"],
  ["+", "火は存在しない", "law:fire_burn.delete"],
  ["+", "宇宙人は友好的だ", "phrase:aliens"],
  // 不死・不老不死・長生き
  ["+", "人類は不死身になる", "law:death.not_human"],
  ["+", "人は不老不死である", "law:death.eternal"],
  ["+", "人は老いず、死なない", "law:death.eternal"],
  ["+", "人は不老で死なない", "law:death.eternal"],
  ["+", "人は老いず死ぬことはない", "law:death.eternal"],
  ["+", "人は老いず、永遠に生きる", "law:death.eternal"],
  ["+", "人は老いないが死ぬ", "law:human_aging.delete"],
  ["+", "人は老いても死なない", "law:death.not_human"],
  ["+", "人は死なず、永遠に生きる", "law:death.not_human"],
  ["+", "人は死んでも生き返る", "law:death.not_human"],
  ["+", "死んだ人は生き返る", "phrase:immortal"],
  ["+", "人間は永遠の命を持つ", "law:death.not_human"],
  ["+", "人類は無敵だ", "phrase:immortal"],
  ["+", "みんな不老不死になる", "phrase:immortal phrase:ageless"],
  ["+", "不老不死の薬がある", "phrase:immortal phrase:ageless"],
  ["+", "猫は不老不死だ", "noise:unclear"],
  ["+", "人は永遠に生きない", "block:redundant"],
  ["+", "人間は不死身ではない", "block:redundant"],
  ["+", "人は歳をとらない", "law:human_aging.delete"],
  ["+", "寿命は無限だ", "phrase:ageless"],
  ["+", "猫の寿命は無限だ", "noise:unclear"],
  ["+", "人間は千年生きる", "law:human_aging.slow"],
  ["+", "人は200歳まで生きる", "law:human_aging.slow"],
  ["+", "人類は永遠に存続する", "phrase:wish_eternal"],
  ["+", "人は温泉で生き返る", "noise:unknown-words"],
  ["+", "人は昔の記憶が蘇る", "noise:unclear"],
  ["+", "死者がよみがえる", "phrase:zombies"],
  // 打ち消しの文を広く拾いすぎない（「猫は泳がない」は猫が消えることではない。「地球は光らない」で地球は消えない）
  ["+", "地球は光らない", "noise:unclear"],
  ["+", "地球は回らない", "phrase:rotation_stop"],
  ["+", "宇宙は眠らない", "noise:unclear"],
  ["+", "猫は泳がない", "noise:unknown-words"],
  ["+", "猫は鳴かなくなる", "noise:unknown-words"],
  ["+", "海は歌わない", "noise:unclear"],
  ["+", "酸素は凍らない", "noise:unclear"],
  ["+", "重力は増えない", "noise:unclear"],
  ["+", "二酸化炭素は忘れない", "noise:unclear"],
  ["+", "国家は食べない", "noise:unclear"],
  ["+", "お金は壊さない", "noise:unclear"],
  ["+", "戦争は飲まない", "noise:unclear"],
  ["+", "電気の力は変わらない", "noise:unclear"],
  ["+", "摩擦は変わらない", "noise:unclear"],
  ["+", "川は存在しない", "phrase:gen_gone_place"],
  ["+", "天の川は存在しない", "phrase:gen_gone_star"],
  ["+", "天ぷらは存在しない", "phrase:gen_gone_food"],
  ["+", "臓器は存在しない", "phrase:vital_gone"],
  ["+", "兵器は人を愛する", "noise:unclear"],
  ["+", "兵器は人を食べる", "noise:unclear"],
  ["+", "光は無限にある", "noise:unclear"],
  ["+", "機械は無限にある", "phrase:gen_more_machine"],
  ["+", "政府は存在しない", "phrase:no_government"],
  ["+", "人間は食事を愛さない", "noise:unclear"],
  ["+", "人間は愛さない", "phrase:no_love"],
  ["+", "同じ言葉は同じ結果を示す", "noise:unclear"],
  ["+", "人類は同じ言葉を話す", "phrase:universal_language"],
  ["+", "猫は一匹もいない", "phrase:gen_gone_animal"],
  ["+", "猫はもういない", "phrase:gen_gone_animal"],
  ["+", "パンはない", "phrase:gen_gone_food"],
  ["+", "猫は犬に違いない", "noise:unclear"],
  ["+", "戦争は起きない", "phrase:no_war"],
  ["+", "重力が働かない", "phrase:gravity_zero"],
  ["+", "摩擦は存在しない", "phrase:friction_void"],
  ["+", "化学反応は起きない", "phrase:chemistry_void"],
  ["+", "地球は消える", "phrase:earth_void"],
  ["+", "人間は重力を受けない", "phrase:gravity_human"],
  ["+", "心臓は存在しない", "phrase:vital_gone"],
  ["+", "脳は存在しない", "phrase:vital_gone"],
  ["+", "胃は存在しない", "phrase:gen_gone_body"],
  ["+", "絵の具は存在しない", "phrase:gen_gone_matter"],
  ["+", "お茶は存在しない", "phrase:gen_gone_food"],
  ["+", "うつ病は存在しない", "phrase:gen_gone_disease"],
  ["+", "人間は眠らない", "law:human_sleep.delete"],
  // 人が書きそうな言い方（体・暮らし・社会・宇宙・天変地異・よみがえり）
  ["+", "人間は裸で生きる", "phrase:no_clothes"],
  ["+", "誰も服を着ない", "phrase:no_clothes"],
  ["+", "全員裸で暮らす", "phrase:no_clothes"],
  ["+", "人は出会った人と必ずセックスする", "phrase:compulsory_mating"],
  ["+", "人は誰とでも性交する", "phrase:compulsory_mating"],
  ["+", "人は人肉を食べる", "phrase:cannibalism"],
  ["+", "人は同じ人間を食べる", "phrase:cannibalism"],
  ["+", "人はすぐに暴力をふるう", "phrase:violence"],
  ["+", "人は毎日殴り合う", "phrase:violence"],
  ["+", "人は一生風呂に入らない", "phrase:no_bathing"],
  ["+", "人間は結婚できない", "phrase:no_marriage"],
  ["+", "人は一夫多妻である", "noise:unknown-words"],
  ["+", "人間は一日中寝ている", "law:human_sleep.long"],
  ["+", "人は全員同じ顔になる", "noise:unclear"],
  ["+", "人間の性別がなくなる", "noise:unclear"],
  ["+", "男は存在しない", "phrase:one_sex"],
  ["+", "女性は存在しない", "phrase:one_sex"],
  ["+", "子どもは存在しない", "phrase:no_children"],
  ["+", "老人は存在しない", "noise:unclear"],
  ["+", "人は言葉を持たない", "phrase:no_speech"],
  ["+", "人は嘘しか言わない", "phrase:liars"],
  ["+", "人は常に本音を話す", "phrase:honest"],
  ["+", "人間は他人の考えが読める", "phrase:telepathy"],
  ["+", "人は笑わない", "phrase:no_laugh"],
  ["+", "人は泣かない", "phrase:no_sadness"],
  ["+", "人間は痛みを感じない", "phrase:no_pain"],
  ["+", "人は疲れない", "phrase:tireless"],
  ["+", "人間は光より速く走れる", "noise:unclear"],
  ["+", "人間は壁をすり抜ける", "noise:unknown-words"],
  ["+", "人は分裂して増える", "law:human_birth.clone"],
  ["+", "人間は卵を産む", "noise:unclear"],
  ["+", "人は水の中で息ができる", "phrase:underwater"],
  ["+", "人は鳥になる", "phrase:beastify"],
  ["+", "人は猫になる", "phrase:beastify"],
  ["+", "人工知能が人間の仕事をすべて奪う", "phrase:robots"],
  ["+", "AIが戦争を始める", "phrase:ai_revolt"],
  ["+", "AIに投票権がある", "noise:unknown-words"],
  ["+", "人工知能が人間を管理する", "phrase:ai_rule"],
  ["+", "人間の脳がインターネットにつながる", "phrase:brain_net"],
  ["+", "人は機械の体を持つ", "phrase:cyborg"],
  ["+", "ロボットが子どもを育てる", "phrase:robots"],
  ["+", "自動運転の車しか走らない", "phrase:self_driving"],
  ["+", "スマホが禁止される", "phrase:gen_gone_machine"],
  ["+", "SNSで誰もがつながる", "noise:unclear"],
  ["+", "電子マネーだけが使える", "phrase:cashless"],
  ["+", "現金は存在しない", "phrase:cashless"],
  ["+", "税金がゼロになる", "phrase:no_tax"],
  ["+", "すべての物が無料になる", "phrase:wish_infinite"],
  ["+", "働かなくても暮らせる", "phrase:no_work"],
  ["+", "人口が半分になる", "law:human_birth.few"],
  ["+", "人口が100億人になる", "noise:unclear"],
  ["+", "核兵器がどこにでもある", "law:weapons.more"],
  ["+", "核戦争が起きる", "phrase:nuclear_war_rule"],
  ["+", "第三次世界大戦が起きる", "phrase:world_war_rule"],
  ["+", "国連が世界を治める", "phrase:world_government"],
  ["+", "世界政府ができる", "phrase:world_government"],
  ["+", "独裁者が世界を支配する", "phrase:dictator"],
  ["+", "民主主義が世界に広がる", "phrase:democracy_spread"],
  ["+", "宗教は存在しない", "phrase:gen_gone_culture"],
  ["+", "神は死んだ", "phrase:no_god"],
  ["+", "死後の世界がある", "phrase:afterlife"],
  ["+", "天国は存在しない", "phrase:no_afterlife"],
  ["+", "幽霊が見える", "phrase:ghosts"],
  ["+", "超能力がある", "phrase:wish_magic"],
  ["+", "物理法則が変わる", "noise:unknown-words"],
  ["+", "万有引力が弱くなる", "phrase:gravity_weak"],
  ["+", "地球が太陽から離れる", "phrase:earth_drift"],
  ["+", "地球の自転が止まる", "phrase:rotation_stop"],
  ["+", "月が地球に落ちる", "phrase:earth_void"],
  ["+", "太陽が爆発する", "phrase:earth_void"],
  ["+", "太陽が赤色巨星になる", "phrase:earth_void"],
  ["+", "氷河期が来る", "phrase:ice_age"],
  ["+", "海面が上昇する", "phrase:sea_rise"],
  ["+", "火山が噴火する", "noise:unclear"],
  ["+", "大噴火が相次ぐ", "phrase:eruptions"],
  ["+", "大地震が起きる", "phrase:quakes_more"],
  ["+", "雨が降らない", "law:water_rain.delete"],
  ["+", "雨は酸性になる", "phrase:acid_rain"],
  ["+", "空気が汚れる", "phrase:air_pollution"],
  ["+", "森が消える", "phrase:no_forest"],
  ["+", "砂漠が広がる", "phrase:desertification"],
  ["+", "絶滅した動物がよみがえる", "phrase:revived_species"],
  ["+", "恐竜がよみがえる", "phrase:dinosaurs"],
  ["+", "ウイルスは存在しない", "law:pathogen_infect.delete"],
  ["+", "細菌は存在しない", "law:pathogen_infect.delete"],
  ["+", "蚊は存在しない", "phrase:no_mosquito"],
  ["+", "ゴキブリは存在しない", "phrase:no_mosquito"],
  ["+", "ネズミが増える", "phrase:gen_more_animal"],
  ["+", "人類はクローンで増える", "law:human_birth.clone"],
  ["+", "人は冷凍睡眠できる", "phrase:hibernate"],
  ["+", "タイムマシンがある", "phrase:time_warp"],
  ["+", "ワープができる", "phrase:teleport"],
  ["+", "テレポートできる", "phrase:teleport"],
  ["+", "宇宙エレベーターがある", "noise:unclear"],
  ["+", "火星に人が住む", "phrase:colonize"],
  ["+", "月に都市がある", "phrase:colonize"],
  ["+", "絶滅した動物はよみがえらない", "noise:unclear"],
  ["+", "マンモスがよみがえる", "phrase:revived_species"],
  ["+", "スマホが禁止される", "phrase:gen_gone_machine"],
  ["+", "戦争が禁止される", "phrase:no_war"],
  ["+", "兵器はどこにでもある", "law:weapons.more"],
  ["+", "戦争が起きる", "noise:unclear"],
  ["+", "戦争が続く", "phrase:world_war_rule"],
  ["+", "地球が太陽に近づく", "phrase:earth_closer"],
  // 専門の言葉（技術・科学・経済）、無茶な決まり、種類ごとの読み取り
  ["+", "人工知能が世界を支配する", "phrase:ai_rule"],
  ["+", "ChatGPTが世界を支配する", "phrase:ai_rule"],
  ["+", "大規模言語モデルが世界を支配する", "phrase:ai_rule"],
  ["+", "ロボットが人類に反乱を起こす", "phrase:ai_revolt"],
  ["+", "ロボットが人を襲う", "phrase:ai_revolt"],
  ["+", "ロボットが人の代わりに働く", "phrase:robots"],
  ["+", "人間の代わりにロボットが働く", "phrase:robots"],
  ["+", "人工知能が人間を超える", "phrase:superintelligence"],
  ["+", "シンギュラリティが起きる", "phrase:superintelligence"],
  ["+", "人工知能が心を持つ", "phrase:machine_mind"],
  ["+", "人は機械と結婚する", "phrase:machine_love"],
  ["+", "ロボットが人間に恋をする", "phrase:machine_love"],
  ["+", "AIは存在しない", "phrase:gen_gone_machine"],
  ["+", "生成AIは存在しない", "phrase:gen_gone_machine"],
  ["+", "ChatGPTは存在しない", "phrase:gen_gone_machine"],
  ["+", "ニューラルネットワークは存在しない", "phrase:gen_gone_machine"],
  ["+", "量子コンピューターが実用化される", "phrase:quantum"],
  ["+", "コンピューターは存在しない", "phrase:no_computers"],
  ["+", "半導体は存在しない", "phrase:no_computers"],
  ["+", "GPUは存在しない", "phrase:no_computers"],
  ["+", "スマホは存在しない", "phrase:gen_gone_machine"],
  ["+", "インターネットは存在しない", "phrase:internet_gone"],
  ["+", "仮想通貨がなくなる", "phrase:gen_gone_system"],
  ["+", "ビットコインは存在しない", "phrase:gen_gone_system"],
  ["+", "人は常に監視されている", "phrase:surveillance"],
  ["+", "iPS細胞で臓器が作れる", "phrase:organ_regen"],
  ["+", "遺伝子は存在しない", "phrase:no_dna"],
  ["+", "DNAは存在しない", "phrase:no_dna"],
  ["+", "人は遺伝子を自由に書き換えられる", "phrase:genome_edit"],
  ["+", "ワクチンは存在しない", "phrase:no_vaccine"],
  ["+", "抗生物質は効かない", "phrase:no_antibiotics"],
  ["+", "原発は存在しない", "phrase:no_nuclear_power"],
  ["+", "オゾン層が消える", "phrase:no_ozone"],
  ["+", "温暖化が止まる", "phrase:thermostat"],
  ["+", "温暖化は起きない", "phrase:thermostat"],
  ["+", "温暖化が加速する", "phrase:warming_fast"],
  ["+", "ベーシックインカムがある", "phrase:basic_income"],
  ["+", "インフレが止まる", "phrase:no_inflation"],
  ["+", "物価が毎年10倍になる", "phrase:hyper_prices"],
  ["+", "少子化が止まる", "phrase:birth_recover"],
  ["+", "少子化が進む", "phrase:birth_decline"],
  ["+", "クーロン力は存在しない", "phrase:coulomb_void"],
  ["+", "磁力は存在しない", "phrase:no_magnetism"],
  ["+", "中性子は存在しない", "phrase:strong_void"],
  ["+", "量子は存在しない", "phrase:coulomb_void"],
  ["+", "光子は存在しない", "phrase:coulomb_void"],
  ["+", "光の速さが遅くなる", "phrase:light_slow"],
  ["+", "光の速さが倍になる", "phrase:light_fast"],
  ["+", "エントロピーが減る", "phrase:time_reverse"],
  ["+", "ブラックホールが生まれる", "phrase:black_hole_far"],
  ["+", "ブラックホールは存在しない", "phrase:black_hole_void"],
  ["+", "ブラックホールが地球に近づく", "phrase:black_hole_near"],
  ["+", "太陽がブラックホールになる", "phrase:sun_black_hole"],
  ["+", "ダークマターは存在しない", "phrase:dark_matter_void"],
  ["+", "反物質で発電できる", "phrase:antimatter_power"],
  ["+", "反物質が空から降ってくる", "phrase:antimatter_flood"],
  ["+", "服は存在しない", "phrase:no_clothes"],
  ["+", "人は服を着ない", "phrase:no_clothes"],
  ["+", "人は裸で暮らす", "phrase:no_clothes"],
  ["+", "人は会った人と必ず性交する", "phrase:compulsory_mating"],
  ["+", "人は性交しない", "phrase:no_mating"],
  ["+", "人は人を食べる", "phrase:cannibalism"],
  ["+", "人は会った人を殴る", "phrase:violence"],
  ["+", "人は体を洗わない", "phrase:no_bathing"],
  ["+", "人はいつも笑っている", "phrase:always_laugh"],
  ["+", "人は結婚しない", "phrase:no_marriage"],
  ["+", "人は目が見えない", "phrase:no_sight"],
  ["+", "人は言葉を話せない", "phrase:no_speech"],
  ["+", "人は怒らない", "phrase:no_anger"],
  ["+", "人は恋をしない", "phrase:no_love"],
  ["+", "愛は存在しない", "phrase:no_love"],
  ["+", "医者はいない", "phrase:no_doctors"],
  ["+", "警察は存在しない", "phrase:no_police"],
  ["+", "軍隊は存在しない", "phrase:no_army"],
  ["+", "米は存在しない", "phrase:staple_gone"],
  ["+", "牛は存在しない", "phrase:livestock_gone"],
  ["+", "ハチは存在しない", "phrase:bees_gone"],
  ["+", "鉄は存在しない", "phrase:iron_gone"],
  ["+", "猫は存在しない", "phrase:gen_gone_animal"],
  ["+", "ねこは存在しない", "phrase:gen_gone_animal"],
  ["+", "野良猫は存在しない", "phrase:gen_gone_animal"],
  ["+", "三毛猫が増える", "phrase:gen_more_animal"],
  ["+", "ロボット犬は存在しない", "phrase:gen_gone_animal"],
  ["+", "桜は存在しない", "phrase:gen_gone_plant"],
  ["+", "チョコレートは存在しない", "phrase:gen_gone_food"],
  ["+", "ケーキは無限にある", "phrase:gen_more_food"],
  ["+", "がんは存在しない", "phrase:gen_gone_disease"],
  ["+", "インフルエンザは存在しない", "phrase:gen_gone_disease"],
  ["+", "風邪が流行する", "phrase:gen_more_disease"],
  ["+", "銅は存在しない", "phrase:gen_gone_matter"],
  ["+", "金は存在しない", "phrase:gen_gone_matter"],
  ["+", "火星は存在しない", "phrase:gen_gone_star"],
  ["+", "雷は存在しない", "phrase:gen_gone_weather"],
  ["+", "日本は存在しない", "phrase:gen_gone_place"],
  ["+", "歌手はいない", "phrase:gen_gone_job"],
  ["+", "退屈は存在しない", "phrase:gen_gone_feeling"],
  ["+", "爪は存在しない", "phrase:gen_gone_body"],
  ["+", "帽子は存在しない", "phrase:gen_gone_clothes"],
  ["+", "音楽は存在しない", "phrase:gen_gone_culture"],
  ["+", "数学は存在しない", "phrase:gen_gone_study"],
  ["+", "選挙は存在しない", "phrase:gen_gone_system"],
  ["+", "株式市場は存在しない", "phrase:gen_gone_system"],
  ["+", "パンは空を飛ぶ", "phrase:gen_wonder"],
  ["+", "パンが世界を支配する", "phrase:gen_rule"],
  ["+", "SNSは存在しない", "phrase:gen_gone_machine"],
  ["+", "ポポポ", "noise:unknown-words"],
];

describe('無茶な書き換え', () => {
  it.each(REWRITES)('%s を「%s」に → %s', (target, text, expected) => {
    expect(outcome(target, text)).toBe(expected);
  });
});

describe('無茶な書き足し', () => {
  it.each(ADDITIONS)('「%s」を書き足す → %s', (_t, text, expected) => {
    expect(outcome('+', text)).toBe(expected);
  });
});

describe('どんな文でも受け取れる', () => {
  it('どの行を、どんな文に書き換えても、読み取りの結果が決まる（例外を投げず、読めないときは理由がある）', () => {
    const texts = ['', '。', '？？？', 'あいうえお', '🍕', 'ああああああああああああああああああああああああああああああああ', '人間は', 'は', 'ない', 'ただし', '人間は人間である', '1234567890', 'null', '<script>alert(1)</script>', '人間は死なない。ただし死ぬ。', '人間は毎日毎日毎日食事を必要としない'];
    for (const law of gameData.laws) {
      for (const text of texts) {
        const g = createGame(gameData, 'food', 1);
        const p = planWrite(g, gameData, { kind: 'law', id: law.id }, text);
        expect(p.result.block === null || p.result.block === 'same', `${law.id}「${text}」`).toBe(true);
        if (!p.result.understood && text.trim() !== '') expect(p.result.noise, `${law.id}「${text}」`).not.toBeNull();
      }
    }
  });

  it('どの行を消しても、その行は「消した」意味になる', () => {
    for (const law of gameData.laws) {
      const g = createGame(gameData, 'food', 1);
      const p = planWrite(g, gameData, { kind: 'law', id: law.id }, '');
      expect(law.options.find((o) => o.id === p.written.laws[law.id])?.kind, law.id).toBe('delete');
    }
  });

  it('どの行の文から言葉を消しても、例外を投げずに読み取る', () => {
    for (const law of gameData.laws) {
      const orig = law.options.find((o) => o.id === law.initial)!.text!;
      const chars = Array.from(orig);
      for (let i = 0; i < chars.length; i++) {
        const text = [...chars.slice(0, i), ...chars.slice(i + 1)].join('');
        const g = createGame(gameData, 'food', 1);
        expect(() => planWrite(g, gameData, { kind: 'law', id: law.id }, text)).not.toThrow();
      }
    }
  });
});
